"""initial schema

Revision ID: 209f7d2dd6b1
Revises: 
Create Date: 2026-10-05 06:10:35.063852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '209f7d2dd6b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.create_table('agents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'revoked')", name=op.f('ck_agents_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_agents_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents')),
    sa.UniqueConstraint('api_key_hash', name=op.f('uq_agents_api_key_hash')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_agents_tenant_id_id')
    )
    op.create_table('allowlist',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cidr', postgresql.CIDR(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_allowlist_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allowlist')),
    sa.UniqueConstraint('tenant_id', 'cidr', name='uq_allowlist_tenant_cidr')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_log_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_tenant_created', 'audit_log', ['tenant_id', 'created_at'], unique=False)
    op.create_table('enrollment_codes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_enrollment_codes_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollment_codes')),
    sa.UniqueConstraint('code_hash', name=op.f('uq_enrollment_codes_code_hash'))
    )
    op.create_table('notification_channels',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('address', sa.String(length=320), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('email', 'telegram')", name=op.f('ck_notification_channels_type_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_notification_channels_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_channels')),
    sa.UniqueConstraint('tenant_id', 'type', 'address', name='uq_notification_channels_tenant_type_address')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_users_email_lowercase')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_users_tenant_id_id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("explanation_status IN ('pending', 'ready', 'fallback')", name=op.f('ck_alerts_explanation_status_valid')),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_alerts_severity_valid')),
    sa.CheckConstraint("status IN ('open', 'allowed', 'blocked', 'dismissed', 'expired')", name=op.f('ck_alerts_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id', 'agent_id'], ['agents.tenant_id', 'agents.id'], name=op.f('fk_alerts_tenant_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'decided_by'], ['users.tenant_id', 'users.id'], name=op.f('fk_alerts_tenant_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_alerts_tenant_id_id')
    )
    op.create_index('ix_alerts_tenant_created', 'alerts', ['tenant_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_alerts_tenant_dedupe', 'alerts', ['tenant_id', 'dedupe_key', 'created_at'], unique=False)
    op.create_table('flows',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('start_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('src_ip', postgresql.INET(), nullable=False),
    sa.Column('dst_ip', postgresql.INET(), nullable=False),
    sa.Column('src_port', sa.Integer(), nullable=False),
    sa.Column('dst_port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('fwd_packets', sa.BigInteger(), nullable=False),
    sa.Column('bwd_packets', sa.BigInteger(), nullable=False),
    sa.Column('fwd_bytes', sa.BigInteger(), nullable=False),
    sa.Column('bwd_bytes', sa.BigInteger(), nullable=False),
    sa.Column('pkt_len_mean', sa.Float(), nullable=False),
    sa.Column('pkt_len_std', sa.Float(), nullable=False),
    sa.Column('iat_mean_s', sa.Float(), nullable=False),
    sa.Column('syn_count', sa.BigInteger(), nullable=False),
    sa.Column('rst_count', sa.BigInteger(), nullable=False),
    sa.Column('fin_count', sa.BigInteger(), nullable=False),
    sa.Column('uniq_dst_ports_60s', sa.BigInteger(), nullable=False),
    sa.Column('uniq_dst_ips_60s', sa.BigInteger(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("protocol IN ('tcp', 'udp', 'icmp', 'other')", name=op.f('ck_flows_protocol_valid')),
    sa.CheckConstraint('src_port BETWEEN 0 AND 65535 AND dst_port BETWEEN 0 AND 65535', name=op.f('ck_flows_ports_valid')),
    sa.ForeignKeyConstraint(['tenant_id', 'agent_id'], ['agents.tenant_id', 'agents.id'], name=op.f('fk_flows_tenant_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'flow_id', name=op.f('pk_flows'))
    )
    op.create_index('ix_flows_tenant_start', 'flows', ['tenant_id', 'start_ts'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('commands',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=False),
    sa.Column('ttl_minutes', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.String(length=200), nullable=True),
    sa.CheckConstraint("(type = 'block_ip' AND ttl_minutes IS NOT NULL AND ttl_minutes BETWEEN 1 AND 1440) OR (type = 'unblock_ip' AND ttl_minutes IS NULL)", name=op.f('ck_commands_ttl_matches_type')),
    sa.CheckConstraint("state IN ('pending', 'applied', 'failed', 'expired', 'reverted')", name=op.f('ck_commands_state_valid')),
    sa.CheckConstraint("type IN ('block_ip', 'unblock_ip')", name=op.f('ck_commands_type_valid')),
    sa.ForeignKeyConstraint(['tenant_id', 'agent_id'], ['agents.tenant_id', 'agents.id'], name=op.f('fk_commands_tenant_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'alert_id'], ['alerts.tenant_id', 'alerts.id'], name=op.f('fk_commands_tenant_id_alerts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commands'))
    )
    op.create_index('ix_commands_tenant_agent_state', 'commands', ['tenant_id', 'agent_id', 'state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_commands_tenant_agent_state', table_name='commands')
    op.drop_table('commands')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_flows_tenant_start', table_name='flows')
    op.drop_table('flows')
    op.drop_index('ix_alerts_tenant_dedupe', table_name='alerts')
    op.drop_index('ix_alerts_tenant_created', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('users')
    op.drop_table('notification_channels')
    op.drop_table('enrollment_codes')
    op.drop_index('ix_audit_log_tenant_created', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('allowlist')
    op.drop_table('agents')
    op.drop_table('tenants')
    # ### end Alembic commands ###
